{
  "sksl": {
    "entrypoint": "simple_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 resolution;\nuniform vec2 pointer;\nuniform float t;\nuniform float dt;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_distance_example()\n{\n    vec2 st = FLT_flutter_local_FlutterFragCoord() / resolution;\n    st.x *= (resolution.x / resolution.y);\n    st = (st * 2.0) - vec2(1.0);\n    float d = length(abs(st) - vec2(0.5));\n    vec3 color = vec3(0.0);\n    color = vec3(fract(d * 10.0));\n    fragColor = vec4(color, 1.0);\n}\n\nvoid FLT_main()\n{\n    FLT_flutter_local_distance_example();\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "pointer",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "t",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "dt",
        "rows": 1,
        "type": 10
      }
    ]
  }
}