{
  "sksl": {
    "entrypoint": "bg_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform float iTime;\nuniform shader iChannel1;\nuniform half2 iChannel1_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec2 FLT_flutter_local_rotate(vec2 uv, float angle)\n{\n    float cosA = cos(angle);\n    float sinA = sin(angle);\n    mat2 rotationMatrix = mat2(vec2(cosA, -sinA), vec2(sinA, cosA));\n    vec2 centeredUv = uv - vec2(0.5);\n    centeredUv = rotationMatrix * centeredUv;\n    return centeredUv + vec2(0.5);\n}\n\nvec2 FLT_flutter_local_applyDistortion(vec2 uv)\n{\n    float distortX = sin((uv.y * 15.0) + (iTime * 0.066666670143604278564453125)) * 0.20000000298023223876953125;\n    float distortY = cos((uv.x * 15.0) + (iTime * 0.066666670143604278564453125)) * 0.20000000298023223876953125;\n    return uv + vec2(distortX, distortY);\n}\n\nvec2 FLT_flutter_local_wrapUv(vec2 uv)\n{\n    return uv - floor(uv);\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = FLT_flutter_local_FlutterFragCoord() / iResolution;\n    vec2 param = uv_1;\n    float param_1 = iTime * 0.066666670143604278564453125;\n    uv_1 = FLT_flutter_local_rotate(param, param_1);\n    vec2 param_2 = uv_1;\n    uv_1 = FLT_flutter_local_applyDistortion(param_2);\n    vec2 param_3 = uv_1;\n    uv_1 = FLT_flutter_local_wrapUv(param_3);\n    fragColor = iChannel1.eval(iChannel1_size * ( uv_1));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "iChannel1",
        "rows": 1,
        "type": 12
      }
    ]
  }
}