{
  "sksl": {
    "entrypoint": "bg_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec2 FLT_flutter_local_applyDistortion(vec2 uv)\n{\n    float distortX = sin((uv.y * 10.0) + (uTime * 0.5)) * 0.20000000298023223876953125;\n    float distortY = cos((uv.x * 10.0) + (uTime * 0.5)) * 0.20000000298023223876953125;\n    return uv + vec2(distortX, distortY);\n}\n\nvec2 FLT_flutter_local_applyZoom(vec2 uv, float zoomFactor, vec2 zoomCenter)\n{\n    vec2 centeredUv = uv - zoomCenter;\n    centeredUv /= vec2(zoomFactor);\n    return centeredUv + zoomCenter;\n}\n\nvoid FLT_main()\n{\n    vec2 uv_1 = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 param = uv_1;\n    vec2 distortedUv = FLT_flutter_local_applyDistortion(param);\n    vec2 param_1 = distortedUv;\n    float param_2 = 1.5;\n    vec2 param_3 = vec2(0.5);\n    vec2 zoomedUv = FLT_flutter_local_applyZoom(param_1, param_2, param_3);\n    zoomedUv = clamp(zoomedUv, vec2(0.0), vec2(1.0));\n    vec4 color = uTexture.eval(uTexture_size * ( zoomedUv));\n    fragColor = color;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}